### ISSUE TITLE
You've been a long time in elite sport.

### ISSUE THREAD

**Issue by pbar1** [charleslsteele/github-slideshow#4]
You regard yourself as a _team leader_. What on earth possessed you to _show the way_ to first toime Olympians to go and act with such disregard for your teammates?

**Comment by charleslsteele** [comment]
Did you ever _cross your mind_ in the hotel room that you were doing wrong? _I did cross my mind_ that that was a bahd idea and for that, I'm truly sorry.

**Comment by pbar1** [comment]
Thank you for your comment Eamon, now lets get a take from James who looks loike he's been sweating his pants off.

**Comment by Williamlsteele** [comment]
truly sorry, tebbly sorry~ and for that, i'm truly sorry
